"""Update migration

Revision ID: 85a8a9f9ab06
Revises: ae4d235cb2e7
Create Date: 2025-05-02 05:56:04.902973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a8a9f9ab06'
down_revision: Union[str, None] = 'ae4d235cb2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_descriptions', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    op.drop_column('job_descriptions', 'created_by')
    # ### end Alembic commands ###
