"""Update migration

Revision ID: 9f79c8317b9d
Revises: 781b80e4d0b7
Create Date: 2025-05-02 05:49:46.806002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f79c8317b9d'
down_revision: Union[str, None] = '781b80e4d0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_descriptions_created_by_fkey', 'job_descriptions', type_='foreignkey')
    op.drop_column('job_descriptions', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('job_descriptions_created_by_fkey', 'job_descriptions', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
