"""Update migration

Revision ID: d852f1946922
Revises: 3943dca03add
Create Date: 2025-05-02 06:14:18.325214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd852f1946922'
down_revision: Union[str, None] = '3943dca03add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('candidate_feedbacks_created_by_fkey', 'candidate_feedbacks', type_='foreignkey')
    op.drop_column('candidate_feedbacks', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_feedbacks', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('candidate_feedbacks_created_by_fkey', 'candidate_feedbacks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
