"""Update migration

Revision ID: fef15c4ef4d8
Revises: 6a455d982ffa
Create Date: 2025-05-03 03:10:18.431964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef15c4ef4d8'
down_revision: Union[str, None] = '6a455d982ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('contract_type', sa.String(length=50), nullable=True))
    op.drop_column('job_descriptions', 'constract_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('constract_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('job_descriptions', 'contract_type')
    # ### end Alembic commands ###
